prop:
#  upload-folder: D:/test/
  upload-folder: C:/Java/apache-tomcat-8.5.27/webapps/newsimg/
  upload-wxfolder: C:/Java/apache-tomcat-8.5.27/webapps/wxnewsimg/
# 配置SpringMVC文件上传限制，默认1M。注意MB要大写，不然报错。SpringBoot版本不同，配置项不同
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB